[package]
name = "redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
derive-new = "0.5.9"
regex = "1.9.5"
tokio = { version = "1.32.0", features = ["full"] }

